### ISSUE TITLE
tips to updating widevine key manually?

### ISSUE THREAD

**Issue by linkinstreet** [thisistyx/sooka-free-channels#1]
Hi, I tried the listed M3U8, and TiviMate is giving me DRM Exception error, while TVIRL is showing 403 forbidden, both usually points to failed widevine key.

Are there any way to update and enter own widevine key for Sooka? For Unifi-TV, there is a guide listed on how to do it. but not for Sooka. 

Thank you

**Comment by thisistyx** [comment]
First, go to the Live TV page, then select Inspect Element and go to "Network". Play the channel. Then, filter by "udrmv3" and then copy the link.

**Comment by linkinstreet** [comment]
That totally works. Thanks!

Might want to add this to the readme
